defaults:
  - _self_

_target_: smort.models.smort.SMORT
nmotionfeats: 76
ntextfeats: 768
latent_dim: 256
ff_size: 1024
num_layers: 12
num_heads: 12
dropout: 0.1
activation: gelu
vae: true
fact: null
sample_mean: false
lmd:
    recons: 1
    joint: 1.0e-3
    latent: 1.0e-5
    kl: 1.0e-4
lr: 1e-4
# viz_interval: -1
viz_interval: 50